import { describe, expect, it, vi } from 'vitest';
import {
  MAX_FEATURE_COUNT,
  DatasetError,
  indexCollection,
  validateCollection,
  validateMetadata,
} from '../src/data/dataset';
import {
  LOCATIONS_PATH,
  METADATA_PATH,
  assetUrl,
  loadLocations,
  loadLocationsOnce,
  resetDatasetCache,
} from '../src/data/load';
import type { LocationProperties } from '../src/types/location';

/**
 * Inline fixtures only. `public/data/cafes.geojson` is generated by a separate pipeline and
 * may not exist, so nothing here may read the real artifact — a test that depended on it
 * would pass or fail depending on someone else's schedule.
 */

function properties(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    id: 'eoy-3f2a1b9c4d5e',
    name: 'EMMY',
    legalName: 'EMH 919 INC',
    street: '919 FULTON STREET',
    neighborhood: null,
    borough: 'Brooklyn',
    zip: '11238',
    type: 'sidewalk',
    status: 'Issued',
    licenseIssued: '2026-06-12',
    licenseExpires: '2030-06-12',
    nta: 'BK0204',
    bbl: '3019770033',
    sid: ['row-1'],
    ...overrides,
  };
}

function feature(overrides: Record<string, unknown> = {}, coordinates: unknown = [-73.9664, 40.6834]) {
  const id = typeof overrides['id'] === 'string' ? overrides['id'] : 'eoy-3f2a1b9c4d5e';
  return {
    type: 'Feature',
    id,
    geometry: { type: 'Point', coordinates },
    properties: properties(),
    ...overrides,
  };
}

/** `feature` with the id kept in step between the feature and its properties. */
function featureWithId(
  id: string,
  propertyOverrides: Record<string, unknown> = {},
  coordinates?: unknown,
) {
  return feature({ id, properties: properties({ id, ...propertyOverrides }) }, coordinates);
}

function collection(features: unknown[] = [feature()]): unknown {
  return { type: 'FeatureCollection', features };
}

function metadata(overrides: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    dataset: 'Dining Out NYC Locations',
    datasetId: 'fpeh-f7ci',
    provider: 'NYC Department of Transportation',
    source: 'https://data.cityofnewyork.us/resource/fpeh-f7ci.json',
    attribution: 'Department of Transportation (DOT)',
    retrievedAt: '2026-09-27T10:15:00Z',
    sourceUpdatedAt: '2026-09-27T06:00:00Z',
    recordCount: 1,
    sourceRowCount: 2,
    contentHash: 'abc123',
    counts: { sidewalk: 1, roadway: 0, both: 0 },
    boroughs: { Brooklyn: 1 },
    ...overrides,
  };
}

function response(body: unknown, init: { status?: number } = {}): Response {
  const status = init.status ?? 200;
  return {
    ok: status >= 200 && status < 300,
    status,
    json: () => Promise.resolve(body),
  } as unknown as Response;
}

describe('validateCollection accepts the contract', () => {
  it('accepts a well-formed FeatureCollection', () => {
    const parsed = validateCollection(collection());
    expect(parsed.type).toBe('FeatureCollection');
    expect(parsed.features).toHaveLength(1);
    expect(parsed.features[0]?.properties).toEqual(properties());
  });

  it('accepts the null-valued optional fields', () => {
    const parsed = validateCollection(
      collection([feature({ properties: properties({ neighborhood: null, nta: null, bbl: null }) })]),
    );
    const first = parsed.features[0]?.properties;
    expect(first?.neighborhood).toBeNull();
    expect(first?.nta).toBeNull();
    expect(first?.bbl).toBeNull();
  });

  it('accepts every dining type and every borough', () => {
    const features = [
      featureWithId('eoy-000000000001', { type: 'sidewalk' }),
      featureWithId('eoy-000000000002', { type: 'roadway' }),
      featureWithId('eoy-000000000003', { type: 'both' }),
      featureWithId('eoy-000000000004', { borough: 'Staten Island' }),
    ];
    expect(validateCollection(collection(features)).features).toHaveLength(4);
  });

  it('rebuilds the feature so downstream code can trust the types', () => {
    const parsed = validateCollection(
      collection([feature({ properties: properties({ zip: '11238' }) })]),
    );
    const first = parsed.features[0];
    expect(first?.geometry.coordinates[0]).toBeCloseTo(-73.9664);
    expect(first?.geometry.coordinates[1]).toBeCloseTo(40.6834);
  });

  it('names the offending path in the error, so a bad artifact is debuggable', () => {
    expect(() =>
      validateCollection(collection([feature({ properties: properties({ zip: 11238 }) })])),
    ).toThrow(/features\[0\]\.properties\.zip must be a string, got the number 11238/);
  });
});

describe('validateCollection rejects a malformed payload', () => {
  it('rejects a non-object root', () => {
    for (const raw of [null, undefined, 42, 'FeatureCollection', []]) {
      expect(() => validateCollection(raw)).toThrow(DatasetError);
    }
  });

  it('rejects the wrong collection type', () => {
    expect(() => validateCollection({ type: 'Feature', features: [] })).toThrow(
      /must be the string "FeatureCollection"/,
    );
    expect(() => validateCollection({ type: 'FeatureCollection' })).toThrow(
      /features must be an array/,
    );
  });

  it('refuses an empty collection rather than rendering a blank map', () => {
    expect(() => validateCollection(collection([]))).toThrow(/refusing to render a blank map/);
  });

  it('refuses an implausible feature count', () => {
    const features = Array.from({ length: 3 }, (_, index) =>
      feature({ id: `eoy-${index.toString(16).padStart(12, '0')}` }),
    );
    expect(MAX_FEATURE_COUNT).toBeGreaterThan(features.length);
    expect(() =>
      validateCollection({ type: 'FeatureCollection', features: { length: 1e9 } }),
    ).toThrow(DatasetError);
  });

  it('rejects a duplicate id, which would corrupt the byId lookup', () => {
    expect(() => validateCollection(collection([feature(), feature()]))).toThrow(
      /duplicate location id eoy-3f2a1b9c4d5e/,
    );
  });
});

describe('validateCollection rejects a wrong-typed or wrong-shaped feature', () => {
  it('rejects a feature that is not a Feature', () => {
    expect(() => validateCollection(collection([feature({ type: 'Point' })]))).toThrow(
      /features\[0\]\.type must be the string "Feature"/,
    );
  });

  it('rejects a mismatched top-level id', () => {
    expect(() => validateCollection(collection([feature({ id: 'eoy-0000000000ff' })]))).toThrow(
      /features\[0\]\.id must be the same id as/,
    );
  });

  it('rejects a non-Point geometry', () => {
    expect(() =>
      validateCollection(
        collection([feature({ geometry: { type: 'LineString', coordinates: [[0, 0], [1, 1]] } })]),
      ),
    ).toThrow(/geometry\.type must be the string "Point"/);
  });

  it('rejects coordinates that are not a numeric pair', () => {
    expect(() => validateCollection(collection([feature({}, 'nope')]))).toThrow(
      /geometry\.coordinates must be a \[lng, lat\] pair/,
    );
    expect(() => validateCollection(collection([feature({}, [-73.9])]))).toThrow(
      /geometry\.coordinates must be a \[lng, lat\] pair/,
    );
    expect(() => validateCollection(collection([feature({}, [-73.9, 'north'])]))).toThrow(
      /coordinates\[1\] must be a finite number/,
    );
    expect(() => validateCollection(collection([feature({}, [-73.9, Number.NaN])]))).toThrow(
      /must be a finite number/,
    );
  });

  it('rejects out-of-range coordinates', () => {
    expect(() => validateCollection(collection([feature({}, [-73.9, 91])]))).toThrow(
      /coordinates\[1\] must be a latitude in \[-90, 90\]/,
    );
    expect(() => validateCollection(collection([feature({}, [-181, 40.7])]))).toThrow(
      /coordinates\[0\] must be a longitude in \[-180, 180\]/,
    );
  });

  it('rejects wrong-typed properties', () => {
    const cases: Array<[string, unknown, RegExp]> = [
      ['id', 12345, /properties\.id must be a string/],
      ['name', null, /properties\.name must be a string/],
      ['legalName', 42, /properties\.legalName must be a string/],
      ['street', [], /properties\.street must be a string/],
      ['zip', 11238, /properties\.zip must be a string/],
      ['status', null, /properties\.status must be a string/],
      ['neighborhood', 7, /properties\.neighborhood must be a string/],
      ['nta', 204, /properties\.nta must be a string/],
      ['bbl', 3019770033, /properties\.bbl must be a string/],
      ['sid', 'row-1', /properties\.sid must be a non-empty array/],
      ['sid', [], /properties\.sid must be a non-empty array/],
    ];
    for (const [key, value, pattern] of cases) {
      expect(() =>
        validateCollection(collection([feature({ properties: properties({ [key]: value }) })])),
      ).toThrow(pattern);
    }
  });

  it('rejects a non-string inside sid', () => {
    expect(() =>
      validateCollection(collection([feature({ properties: properties({ sid: ['ok', 7] }) })])),
    ).toThrow(/properties\.sid\[1\] must be a string/);
  });

  it('rejects an unknown borough', () => {
    for (const borough of ['New Jersey', 'brooklyn', 'Jersey City', '', 7, null]) {
      expect(() =>
        validateCollection(collection([feature({ properties: properties({ borough }) })])),
      ).toThrow(/properties\.borough must be one of the five NYC boroughs/);
    }
  });

  it('rejects an unknown dining type', () => {
    for (const type of ['Patio', 'Sidewalk ', 'BOTH', 3, null]) {
      expect(() =>
        validateCollection(collection([feature({ properties: properties({ type }) })])),
      ).toThrow(/properties\.type must be one of sidewalk \| roadway \| both/);
    }
  });

  it('rejects an id that is not the pipeline id shape', () => {
    for (const id of ['nope', 'eoy-xyz', 'EOY-3F2A1B9C4D5E', 'eoy-3f2a1b9c4d', 'eoy-3f2a1b9c4d5ef']) {
      expect(() => validateCollection(collection([featureWithId(id)]))).toThrow(
        /properties\.id must be an id of the form eoy-<12 hex chars>/,
      );
    }
  });

  it('rejects an empty id', () => {
    // The top-level feature id is checked first, so that is the field named in the error.
    expect(() => validateCollection(collection([featureWithId('')]))).toThrow(
      /features\[0\]\.id must be a non-empty string/,
    );
  });

  it('rejects a licence date that is not a bare YYYY-MM-DD', () => {
    for (const value of [
      '2026-06-12T00:00:00.000Z',
      '06/12/2026',
      '2026-6-12',
      '12 June 2026',
      'yesterday',
    ]) {
      expect(() =>
        validateCollection(
          collection([feature({ properties: properties({ licenseIssued: value }) })]),
        ),
      ).toThrow(/properties\.licenseIssued must be a YYYY-MM-DD calendar date/);
    }
  });

  it('rejects a licence date that is not a string at all', () => {
    expect(() =>
      validateCollection(
        collection([feature({ properties: properties({ licenseIssued: 20260612 }) })]),
      ),
    ).toThrow(/properties\.licenseIssued must be a string, got the number 20260612/);
  });

  it('accepts a null licence date', () => {
    const parsed = validateCollection(
      collection([
        feature({ properties: properties({ licenseIssued: null, licenseExpires: null }) }),
      ]),
    );
    expect(parsed.features[0]?.properties.licenseIssued).toBeNull();
  });

  it('rejects an empty required string', () => {
    expect(() =>
      validateCollection(collection([feature({ properties: properties({ name: '   ' }) })])),
    ).toThrow(/properties\.name must be a non-empty string/);
  });
});

describe('validateMetadata', () => {
  it('accepts the contract', () => {
    const parsed = validateMetadata(metadata());
    expect(parsed.datasetId).toBe('fpeh-f7ci');
    expect(parsed.counts).toEqual({ sidewalk: 1, roadway: 0, both: 0 });
    expect(parsed.sourceUpdatedAt).toBe('2026-09-27T06:00:00Z');
  });

  it('accepts a null sourceUpdatedAt', () => {
    expect(validateMetadata(metadata({ sourceUpdatedAt: null })).sourceUpdatedAt).toBeNull();
  });

  it('rejects a missing required field', () => {
    for (const key of [
      'dataset',
      'datasetId',
      'provider',
      'source',
      'attribution',
      'retrievedAt',
      'recordCount',
      'sourceRowCount',
      'contentHash',
      'counts',
      'boroughs',
    ]) {
      const broken = metadata();
      delete broken[key];
      expect(() => validateMetadata(broken)).toThrow(DatasetError);
    }
  });

  it('rejects a missing dining-type count', () => {
    expect(() => validateMetadata(metadata({ counts: { sidewalk: 1, roadway: 0 } }))).toThrow(
      /counts\.both must be a finite number, got nothing/,
    );
  });

  it('rejects a non-integer or negative count', () => {
    expect(() => validateMetadata(metadata({ recordCount: 1.5 }))).toThrow(
      /recordCount must be a non-negative integer/,
    );
    expect(() => validateMetadata(metadata({ recordCount: -1 }))).toThrow(
      /recordCount must be a non-negative integer/,
    );
  });

  it('rejects a timestamp that is not ISO-8601', () => {
    expect(() => validateMetadata(metadata({ retrievedAt: 'yesterday' }))).toThrow(
      /retrievedAt must be an ISO-8601 timestamp/,
    );
  });

  it('labels errors with the metadata file name', () => {
    expect(() => validateMetadata({})).toThrow(/^metadata\.json:/);
  });
});

describe('indexCollection', () => {
  const features = [
    feature({ id: 'eoy-000000000001', properties: properties({ id: 'eoy-000000000001' }) }, [
      -73.9664, 40.6834,
    ]),
    feature({ id: 'eoy-000000000002', properties: properties({ id: 'eoy-000000000002' }) }, [
      -73.9857, 40.7484,
    ]),
  ];
  const parsed = validateCollection(collection(features));
  const index = indexCollection(parsed);

  it('gives O(1) lookup by id', () => {
    expect(index.byId.get('eoy-000000000002')?.id).toBe('eoy-000000000002');
    expect(index.byId.get('eoy-ffffffffffff')).toBeUndefined();
    expect(index.byId.size).toBe(2);
  });

  it('flattens to a list sharing the same property objects, with no copy', () => {
    expect(index.locations).toHaveLength(2);
    expect(index.locations[0]).toBe(parsed.features[0]?.properties);
  });

  it('exposes coordinates, which LocationProperties does not carry', () => {
    expect(index.coords.get('eoy-000000000001')).toEqual({ lat: 40.6834, lng: -73.9664 });
  });
});

describe('assetUrl', () => {
  it('builds repository-subpath-safe URLs from the deployment base', () => {
    expect(assetUrl(LOCATIONS_PATH, '/')).toBe('/data/cafes.geojson');
    expect(assetUrl(LOCATIONS_PATH, '/repo/')).toBe('/repo/data/cafes.geojson');
    expect(assetUrl(LOCATIONS_PATH, '/repo')).toBe('/repo/data/cafes.geojson');
    expect(assetUrl(LOCATIONS_PATH, './')).toBe('./data/cafes.geojson');
  });

  it('never produces a leading double slash', () => {
    expect(assetUrl(`/${LOCATIONS_PATH}`, '/repo/')).toBe('/repo/data/cafes.geojson');
  });

  it('names the artifacts the pipeline publishes', () => {
    expect(LOCATIONS_PATH).toBe('data/cafes.geojson');
    expect(METADATA_PATH).toBe('data/metadata.json');
  });
});

describe('loadLocations', () => {
  it('fetches both artifacts from the base path and returns a validated dataset', async () => {
    const fetchImpl = vi.fn().mockImplementation((url: string) =>
      Promise.resolve(
        url.endsWith('cafes.geojson') ? response(collection()) : response(metadata()),
      ),
    );

    const dataset = await loadLocations({
      fetchImpl: fetchImpl as unknown as typeof fetch,
      baseUrl: '/eat-outside-nyc/',
    });

    const urls = fetchImpl.mock.calls.map((call) => String(call[0])).sort();
    expect(urls).toEqual([
      '/eat-outside-nyc/data/cafes.geojson',
      '/eat-outside-nyc/data/metadata.json',
    ]);
    expect(dataset.locations).toHaveLength(1);
    expect(dataset.byId.get('eoy-3f2a1b9c4d5e')?.name).toBe('EMMY');
    expect(dataset.metadata.datasetId).toBe('fpeh-f7ci');
  });

  it('rejects loudly on a non-2xx response instead of returning an empty dataset', async () => {
    const fetchImpl = vi.fn().mockResolvedValue(response(null, { status: 404 }));
    await expect(
      loadLocations({ fetchImpl: fetchImpl as unknown as typeof fetch, baseUrl: '/' }),
    ).rejects.toThrow(/failed with status 404/);
  });

  it('rejects loudly on a malformed payload, so the app shows an error not a blank map', async () => {
    const fetchImpl = vi.fn().mockImplementation((url: string) =>
      Promise.resolve(
        url.endsWith('cafes.geojson')
          ? response({ type: 'FeatureCollection', features: 'nope' })
          : response(metadata()),
      ),
    );
    await expect(
      loadLocations({ fetchImpl: fetchImpl as unknown as typeof fetch, baseUrl: '/' }),
    ).rejects.toThrow(DatasetError);
  });

  it('rejects loudly on malformed metadata', async () => {
    const fetchImpl = vi.fn().mockImplementation((url: string) =>
      Promise.resolve(url.endsWith('cafes.geojson') ? response(collection()) : response({})),
    );
    await expect(
      loadLocations({ fetchImpl: fetchImpl as unknown as typeof fetch, baseUrl: '/' }),
    ).rejects.toThrow(/^metadata\.json:/);
  });

  it('accepts a bare AbortSignal as well as an options object', async () => {
    const controller = new AbortController();
    const signals: unknown[] = [];
    const fetchImpl = vi.fn().mockImplementation((url: string, init?: RequestInit) => {
      signals.push(init?.signal);
      return Promise.resolve(
        url.endsWith('cafes.geojson') ? response(collection()) : response(metadata()),
      );
    });

    // The bare-signal overload uses the global fetch, so stub it rather than reaching the
    // network. The options overload takes the fetch implementation directly.
    const original = globalThis.fetch;
    globalThis.fetch = fetchImpl as unknown as typeof fetch;
    try {
      await loadLocations(controller.signal);
    } finally {
      globalThis.fetch = original;
    }

    await loadLocations({ fetchImpl: fetchImpl as unknown as typeof fetch, baseUrl: '/' });
    expect(signals).toHaveLength(4);
    // Only the bare-signal call carries one; the options call without `signal` sends none.
    expect(signals.slice(0, 2)).toEqual([controller.signal, controller.signal]);
    expect(signals.slice(2)).toEqual([undefined, undefined]);
  });

  it('passes the abort signal down to fetch', async () => {
    const controller = new AbortController();
    const signals: unknown[] = [];
    const fetchImpl = vi.fn().mockImplementation((url: string, init?: RequestInit) => {
      signals.push(init?.signal);
      return Promise.resolve(
        url.endsWith('cafes.geojson') ? response(collection()) : response(metadata()),
      );
    });

    await loadLocations({ signal: controller.signal, fetchImpl: fetchImpl as unknown as typeof fetch });
    expect(signals).toEqual([controller.signal, controller.signal]);
  });
});

describe('module-level cache', () => {
  it('shares one network request across repeated callers', async () => {
    resetDatasetCache();
    const fetchImpl = vi.fn().mockImplementation((url: string) =>
      Promise.resolve(
        url.endsWith('cafes.geojson') ? response(collection()) : response(metadata()),
      ),
    );
    const original = globalThis.fetch;
    globalThis.fetch = fetchImpl as unknown as typeof fetch;

    try {
      const [first, second] = await Promise.all([loadLocationsOnce(), loadLocationsOnce()]);
      const third = await loadLocationsOnce();
      expect(fetchImpl).toHaveBeenCalledTimes(2);
      expect(second).toBe(first);
      expect(third).toBe(first);
    } finally {
      globalThis.fetch = original;
      resetDatasetCache();
    }
  });

  it('evicts a rejected promise so the next attempt retries', async () => {
    resetDatasetCache();
    const original = globalThis.fetch;
    const failing = vi.fn().mockResolvedValue(response(null, { status: 500 }));
    globalThis.fetch = failing as unknown as typeof fetch;

    try {
      await expect(loadLocationsOnce()).rejects.toThrow(/status 500/);
      const retry = vi.fn().mockImplementation((url: string) =>
        Promise.resolve(
          url.endsWith('cafes.geojson') ? response(collection()) : response(metadata()),
        ),
      );
      globalThis.fetch = retry as unknown as typeof fetch;
      await expect(loadLocationsOnce()).resolves.toBeDefined();
      expect(retry).toHaveBeenCalledTimes(2);
    } finally {
      globalThis.fetch = original;
      resetDatasetCache();
    }
  });
});

describe('the index is the single source of truth for the UI', () => {
  it('exposes the same object through the list, the map and the detail sheet', async () => {
    const fetchImpl = vi.fn().mockImplementation((url: string) =>
      Promise.resolve(
        url.endsWith('cafes.geojson') ? response(collection()) : response(metadata()),
      ),
    );
    const dataset = await loadLocations({
      fetchImpl: fetchImpl as unknown as typeof fetch,
      baseUrl: '/',
    });

    const fromList: LocationProperties | undefined = dataset.locations[0];
    const fromMap = dataset.byId.get('eoy-3f2a1b9c4d5e');
    const fromSource = dataset.collection.features[0]?.properties;
    expect(fromList).toBe(fromMap);
    expect(fromList).toBe(fromSource);
  });
});
